### ISSUE TITLE
Error when importing typemallow with  marshmallow-3.7.1 

### ISSUE THREAD

**Issue by Rulioos** [adenh93/typemallow#1]
Got an error with last version of marshmallow. In mappings.py field localDateTime doesn't exist anymore. Deleting the line 17 in mappings.py seems to resolve the issue.
Using  marshmallow-3.7.1 . 

Happens when trying to import typemallow:   

![image](https://user-images.githubusercontent.com/33544567/88478102-e337cf00-cf45-11ea-8c33-522933560347.png)

**Comment by fjbardelli** [comment]
The same error, exists any solution?

Thanks

**Comment by kevinvalk** [comment]
Same here, see also: https://github.com/marshmallow-code/marshmallow/blob/31b784fc24ed637c82d87eac35d1a1bd58851f59/docs/upgrading.rst#datetime-leaves-timezone-information-untouched-during-serialization

**Comment by Rulioos** [comment]
I released a new version of typemallow inspired from adhen work that should handle enums and doesn't have the import issue anymore. The package name is typemallow2 , still in test but it should work.
